/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Model.User;
import Model.UserHelper;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        Regisiter = new javax.swing.JButton();
        Login1 = new javax.swing.JButton();
        Login2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        Login.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setLocation(new java.awt.Point(300, 150));
        setMinimumSize(new java.awt.Dimension(500, 380));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Email");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(57, 68, 84, 32);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(57, 118, 84, 29);

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(205, 68, 180, 32);
        getContentPane().add(password);
        password.setBounds(205, 118, 180, 29);

        Regisiter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Regisiter.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\Todolist\\src\\GUI\\reg.png")); // NOI18N
        Regisiter.setText("Regisiter");
        Regisiter.setContentAreaFilled(false);
        Regisiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisiterActionPerformed(evt);
            }
        });
        getContentPane().add(Regisiter);
        Regisiter.setBounds(185, 253, 144, 38);

        Login1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Login1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/User-Interface-Login-icon.png"))); // NOI18N
        Login1.setText("Login");
        Login1.setContentAreaFilled(false);
        Login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login1ActionPerformed(evt);
            }
        });
        getContentPane().add(Login1);
        Login1.setBounds(185, 197, 123, 38);

        Login2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Login2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/forget.png"))); // NOI18N
        Login2.setText("Forget Password");
        Login2.setContentAreaFilled(false);
        Login2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login2ActionPerformed(evt);
            }
        });
        getContentPane().add(Login2);
        Login2.setBounds(185, 309, 183, 38);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/COLOURlovers.com-Lucky_Finds_2.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-6, 0, 500, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
//        UserHelper userhelper = new UserHelper();
//        User user = new User();
//        user = userhelper.IsExist(email.getText(), password.getText());
//        System.out.println(email.getText());
//        if(email.getText().equals("") || password.getText().equals("")){
//            JOptionPane.showMessageDialog(null, "fill the empty boxes");
//        }else{
//            if(user !=null){
//                //JOptionPane.showMessageDialog(null, "exist");
//                this.dispose();
//                SubjectForm l = new SubjectForm(user);
//                l.setVisible(true);
//            }else {
//                JOptionPane.showMessageDialog(null, "the user doesn't exist");
//            }
//        }
    }//GEN-LAST:event_LoginActionPerformed

    private void RegisiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisiterActionPerformed
        this.dispose();
        RegisiterForm f = new RegisiterForm();
        f.setVisible(true);
    }//GEN-LAST:event_RegisiterActionPerformed

    private void Login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login1ActionPerformed
        UserHelper userhelper = new UserHelper();
        User user = new User();
        user = userhelper.IsExist(email.getText(), password.getText());
        System.out.println(email.getText());
        if(email.getText().equals("") || password.getText().equals("")){
            JOptionPane.showMessageDialog(null, "fill the empty boxes");
        }else{
            if(user !=null){
                //JOptionPane.showMessageDialog(null, "exist");
                this.dispose();
                SubjectForm l = new SubjectForm(user);
                l.setVisible(true);
            }else {
                JOptionPane.showMessageDialog(null, "the user doesn't exist");
            }
        }
    }//GEN-LAST:event_Login1ActionPerformed

    private void Login2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login2ActionPerformed
        this.dispose();
        forgotpass f = new forgotpass();
        f.setVisible(true);
    }//GEN-LAST:event_Login2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JButton Login1;
    private javax.swing.JButton Login2;
    private javax.swing.JButton Regisiter;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
