/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Model.Subject;
import Model.SubjectHelper;
import Model.User;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mekki
 */

public class SubjectForm extends javax.swing.JFrame {

//   public boolean isCellEditable(int row, int column)
//{
//    if (column != 2 && subjectTable.getValueAt(row, 2) == null)
//    {
//        return false;
//    }
//    return true;
//}
    /**
     * Creates new form First_GUI
     */
    DefaultTableModel dtm = new DefaultTableModel();
    public SubjectForm() {
        initComponents();
    }
    
    User user;
    ArrayList<Subject> sub = new ArrayList<>();
    public SubjectForm(User u) {
        initComponents();
        user = u;
        SubjectHelper ss = new SubjectHelper();
        
        sub=(ArrayList<Subject>)ss.SelectAll(user.getId());
        subjectTable.setModel(dtm);
        dtm.addColumn("subjectid");
        dtm.addColumn("subject");
        for(int i=0;i<sub.size();i++){
            dtm.addRow(new Object[]{sub.get(i).getId(),sub.get(i).getSubject()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addSub = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        subjectTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Title = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        savechanges = new javax.swing.JButton();
        DeleteSubject = new javax.swing.JButton();
        showTasks = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Subject");
        setLocation(new java.awt.Point(300, 150));
        setMinimumSize(new java.awt.Dimension(480, 365));
        setResizable(false);
        getContentPane().setLayout(null);

        addSub.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addSub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/1448424154_sign-add.png"))); // NOI18N
        addSub.setText("add Subject");
        addSub.setContentAreaFilled(false);
        addSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubActionPerformed(evt);
            }
        });
        getContentPane().add(addSub);
        addSub.setBounds(310, 230, 139, 29);

        subjectTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SubjectId", "Subject"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(subjectTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 440, 100);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("To Do List");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 20, 69, 17);

        Title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitleActionPerformed(evt);
            }
        });
        getContentPane().add(Title);
        Title.setBounds(60, 230, 120, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("New Subject");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 210, 100, 17);

        savechanges.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        savechanges.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/1448424030_floppy-disk.png"))); // NOI18N
        savechanges.setText("Save Changes");
        savechanges.setContentAreaFilled(false);
        savechanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savechangesActionPerformed(evt);
            }
        });
        getContentPane().add(savechanges);
        savechanges.setBounds(300, 290, 170, 33);

        DeleteSubject.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DeleteSubject.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\Todolist\\src\\GUI\\1448423806_Complete_Symbol.png")); // NOI18N
        DeleteSubject.setText("Complete");
        DeleteSubject.setContentAreaFilled(false);
        DeleteSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteSubjectActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteSubject);
        DeleteSubject.setBounds(300, 260, 140, 25);

        showTasks.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        showTasks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/1448425835_show_property.png"))); // NOI18N
        showTasks.setText("Show Tasks");
        showTasks.setContentAreaFilled(false);
        showTasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTasksActionPerformed(evt);
            }
        });
        getContentPane().add(showTasks);
        showTasks.setBounds(40, 290, 150, 30);

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/inside-logout-icon.png"))); // NOI18N
        Logout.setContentAreaFilled(false);
        Logout.setFocusPainted(false);
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout);
        Logout.setBounds(10, 10, 40, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\Todolist\\src\\GUI\\COLOURlovers.com-Lucky_Finds_2.png")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-6, 0, 480, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTasksActionPerformed
        // TODO add your handling code here:
        int row= subjectTable.getSelectedRow();
        //System.out.println(row);
        if(row!=-1){
        int SubId=(int)subjectTable.getValueAt(row, 0);
        TaskForm atask=new TaskForm(SubId);
        
        atask.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_showTasksActionPerformed

    private void addSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubActionPerformed
        Subject subject = new Subject();
        SubjectHelper subjecthelper = new SubjectHelper();
        if(!Title.getText().isEmpty())
        {
        subject.setSubject(Title.getText());
        if(!(Title.getText().isEmpty())){
            subjecthelper.AddSubject(subject, user.getId());
            JOptionPane.showMessageDialog(null, "Done !", "Success", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            SubjectForm k = new SubjectForm(user);
            k.setVisible(true);
        }
        }
        else{
             JOptionPane.showMessageDialog(null, "Please enter a subject name", "Erorr", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addSubActionPerformed

    private void DeleteSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteSubjectActionPerformed
        int row= subjectTable.getSelectedRow();
        if(row!=-1){
        int SubId=(int)subjectTable.getValueAt(row, 0);
        System.out.println(SubId);
        SubjectHelper subjecthelper = new SubjectHelper();
        subjecthelper.DeleteSubject(SubId);
        JOptionPane.showMessageDialog(null, "Done !", "Success", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
        SubjectForm k = new SubjectForm(user);
        k.setVisible(true);
        }else{
             JOptionPane.showMessageDialog(null, "Please select a subject first", "Erorr", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_DeleteSubjectActionPerformed

    private void TitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TitleActionPerformed

    private void savechangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savechangesActionPerformed
        for(int i=0;i<sub.size();i++){
            SubjectHelper subb = new SubjectHelper();
            subb.UpdateSubject((String) subjectTable.getValueAt(i, 1), (int) subjectTable.getValueAt(i, 0));
        }
        JOptionPane.showMessageDialog(null, "Done !", "Success", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
        SubjectForm k = new SubjectForm(user);
        k.setVisible(true);
    }//GEN-LAST:event_savechangesActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        LoginForm sub=new LoginForm();
        
        sub.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubjectForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteSubject;
    private javax.swing.JButton Logout;
    private javax.swing.JTextField Title;
    private javax.swing.JButton addSub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton savechanges;
    private javax.swing.JButton showTasks;
    private javax.swing.JTable subjectTable;
    // End of variables declaration//GEN-END:variables
}
